apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weatherapi
  template:
    metadata:
      labels:
        app: weatherapi
    spec:
      containers:
      - name: weatherapi
        image: weatheracr001.azurecr.io/weatherapi:v1
        ports:
        - containerPort: 8080
